### ISSUE TITLE
source sequence is illegal/malformed utf-8

### ISSUE THREAD

**Issue by Zorbash** [agorf/thyme#1]
I tried running the scan task in a directory i created just for this purpose and i got the following (snipped) output.

```
rake aborted!
source sequence is illegal/malformed utf-8
/home/zorbash/dev/thyme/lib/thyme/photo.rb:27:in `block in create_from_file'
/home/zorbash/dev/thyme/lib/thyme/photo.rb:25:in `open'
```

Digging into the issue i figured out that due to that changing a possibly malformed value of the exif to a valid one it wouldn't blow up. (the key was "ColorBalanceUnknown").

You could either sanitize the exif hash before saving, or avoid saving all together.

**Comment by agorf** [comment]
Hey. Believe it or not, I don't remember seeing this issue before.

A long shot, but do you remember/have the image that the error occurred on? It will then be possible to reproduce.

Thanks!
